---
- name: Create a role assignment
  hosts: localhost
  connection: local
  tasks:
    - name: Create a role assignment
      azure_rm_roleassignment:
        scope: /subscriptions/09c64ccf-4cab-447d-8cd3-a9c5b8b148f3
        assignee_object_id: ed715b70-47e5-4591-9809-907954077697
        role_definition_id: "/subscriptions/09c64ccf-4cab-447d-8cd3-a9c5b8b148f3/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635"
