---
- name: Create a role assignment
  hosts: localhost
  connection: local
  tasks:
    - name: Create a role assignment
      azure_rm_roleassignment:
        scope: /subscriptions/01b0583a-9196-4ffe-9d0c-5fe9e004e44b
        assignee_object_id: 1caa6788-cf5a-406c-be4a-6bba2185d4ed
        role_definition_id: "/subscriptions/01b0583a-9196-4ffe-9d0c-5fe9e004e44b/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635"
