- name: Azure demo kaynak grubunda 'yes' adında bir VM oluştur
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: VM oluştur
      azure_rm_virtualmachine:
        subscription_id: "011bdceb-fdd1-45cf-8c50-d43e813634a2"  # Abonelik kimliğinizi girin
        resource_group: azure-demo  # Kaynak grubu adınızı buraya girin
        name: yes
        vm_size: Standard_DS1_v2  # Sanal makine boyutunu seçin
        admin_username: azureuser  # Yönetici kullanıcı adınızı belirleyin
        ssh_password_enabled: false  # SSH şifre tabanlı kimlik doğrulamasını etkinleştirin
        ssh_public_keys:
          - path: /home/azureuser/.ssh/authorized_keys
            key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"  # SSH anahtarınızın yolunu belirtin
        image:
          offer: UbuntuServer
          publisher: Canonical
          sku: 18.04-LTS
          version: latest
        state: present  # Sanal makineyi oluştur
      when: "run_test in ['all', 'virtualmachine']"
