---
- name: Create a role assignment
  hosts: localhost
  connection: local
  tasks:
    - name: Create a role assignment
      azure_rm_roleassignment:
        scope: /subscriptions/075a0419-a966-4f60-a993-2d729938d19a
        assignee_object_id: 99a8ec03-aa0d-4e8f-8bfb-731ade884edb
        role_definition_id: "/subscriptions/075a0419-a966-4f60-a993-2d729938d19a/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635"
