---
- name: Assign ownership role to a user in azure-demo resource
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Assign Owner role to a user in azure-demo resource
      azure.azcollection.azure_rm_roleassignment:
        scope: "/subscriptions/011bdceb-fdd1-45cf-8c50-d43e813634a2/resourceGroups/azure-demo"
        role_definition_id: "8e3af657-a8ff-443c-a75c-2fe8c4bcb635"  # Owner rolü kimlik numarası
        assignee_object_id: "ee547a7b-67c1-462a-8e25-3345c8b87943"  # Atanan kullanıcının nesne kimliği
        state: present  # Role atama işleminin oluşturulacağını belirtin
