---
- name: Create Azure VM
  hosts: localhost
  tasks:
    - name: Set Azure CLI Profile Path
      shell: |
        export AZURE_CONFIG_DIR="{{ ansible_env.HOME }}/.azure"
      become: yes

    - name: Create VM
      shell: >
        az vm create --resource-group azure-demo --name myVM --image Debian11 --admin-username azureuser --generate-ssh-keys
      become: yes
