---
- name: Assign ownership role to a user in azure-demo resource
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Assign Owner role to a user in azure-demo resource
      azure.azcollection.azure_rm_roleassignment:
        scope: "/subscriptions/011bdceb-fdd1-45cf-8c50-d43e813634a2/resourceGroups/azure-demo"  # azure-demo kaynağına özgü kapsamı belirtin
        role_definition_id: "18d7d88d-d35e-4fb5-a5c3-7773c20a72d9"  # Owner rolü kimlik numarasını belirtin
        assignee_object_id: "1377e83f-6260-4760-8b50-ed808942a70e"  # Atanan kullanıcının nesne kimliğini belirtin
        state: present  # Role atama işleminin yapılacağını belirtin
