---
- name: Assign Owner role to a user
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Assign Owner role
      azure_rm_roleassignment:
        azure_subscription_id: "011bdceb-fdd1-45cf-8c50-d43e813634a2"
        role_definition_name: "Owner"
        principal_id: "3332608b-ac61-4410-ac0f-fdcd2ebd0499"
