---
- name: Create a role assignment
  hosts: localhost
  connection: local
  tasks:
    - name: Create a role assignment
      azure_rm_roleassignment:
        scope: /subscriptions/01ad0553-71ac-431d-b916-a174264f034b
        assignee_object_id: 54767acf-bfa9-4b45-9abf-36732ce2fab9
        role_definition_id: "/subscriptions/01ad0553-71ac-431d-b916-a174264f034b/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635"
