---
- name: Create a role assignment
  hosts: localhost
  connection: local
  tasks:
      azure_rm_roleassignment:
        scope: /subscriptions/06f08db7-7e7e-4fe8-a448-59f33b8d2506
        assignee_object_id: f194c10d-fcd6-4c47-9e5f-1a00efd0a637
        role_definition_id: "/subscriptions/06f08db7-7e7e-4fe8-a448-59f33b8d2506/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635"
