---
- name: Create a role assignment
  hosts: localhost
  connection: local
  tasks:
    - name: Create a role assignment
      azure_rm_roleassignment:
        scope: /subscriptions/07a655a1-1248-4c8a-9cd3-9b81a1975077
        assignee_object_id: 230e6013-d54b-4426-855d-cfe64a79b1c0
        role_definition_id: "/subscriptions/07a655a1-1248-4c8a-9cd3-9b81a1975077/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635"
